### PR TITLE
Formatted the HTML, JavaScript and CSS for better readability

### PR DESCRIPTION
**Pull request by SerendipityNL**
[I commented on your post. Here's the pull request](https://www.reddit.com/r/factorio/comments/7edszp/i_made_an_online_blueprint_editor/dq4swya/)

### CODE REVIEW

**Comment by Armienn** [comment]
Oh my. Improving the formatting certainly seems like at good move.

**Review by Zeragamba — APPROVED** [review]
Looks like it's just whitespace changes here.

**Comment by camerongillette** [comment]
@SerendipityNL Can you add a new line at the end of the file so git doesn't freak out later?

**Comment by SerendipityNL** [comment]
Fixed the new lines, but now github is throwing the conflict that was created in the Factorio.html file. What's the best way to resolve it?

**Comment by SerendipityNL** [comment]
Okay, I haven't done enough of these pull requests to get this right. Shall I start a new fork and work my way around this mess that I created?

**Comment by camerongillette** [comment]
So @SerendipityNL, I got the original source files from the author which conflicts hard with this PR. However, we can still use some reformatting. Would it be ok for you to either close this one, or rework your commit to accomodate the new source files?

**Comment by SerendipityNL** [comment]
I'll close this one and start a new one!

**Pull request closed without merging**
