### PR TITLE
Preview improvements / maintenance

### PR DESCRIPTION
**Pull request by lessthantrue**
- Preview snaps to grid
- Preview is drawn on top of other items
- Left clicking with an empty preview no longer removes the hovered-over item

### CODE REVIEW

**Comment by lessthantrue** [comment]
Looks like the CSS refactoring pull request broke this feature. This should fix it, as well as improve it a bit.

**Review by Zeragamba — COMMENTED** [review]
Code changes look good to me. I'll have a look at the style changes in the mornin, unless someone else has a look at them

Edit: Damn mobile keyboards

**Comment by camerongillette** [comment]
+1 Looks good to me. Feel free to merge.

**Comment by palexcast** [comment]
This leaves a large empty space in the menu on desktop, since the preview now follows the mouse.
Should probably close that up with the item menu. Opinions?

**Review by Zeragamba — CHANGES_REQUESTED** [review]
I think it would be good to keep that preview in the left sidebar, as it was a good visual clue that you had selected a different item, and it also leaves a large empty space now.

**Comment by Zeragamba** [comment]
going to close and reopen to trigger a travis build

**Review by Zeragamba — CHANGES_REQUESTED** [review]
whoops looks like your npm-debug.log file got included. Can you remove it and add it to the .gitignore file?

**Review by Zeragamba — APPROVED** [review]

**Pull request merged**
